ARG ZULU_VERSION=8u492-jdk
FROM azul/zulu-openjdk:${ZULU_VERSION} AS build

ARG GRADLE_VERSION=7.6.6
ENV GRADLE_HOME=/opt/gradle

RUN apt-get update && apt-get install -y curl unzip \
 && curl -LO https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip \
 && unzip gradle-${GRADLE_VERSION}-bin.zip \
 && mv gradle-${GRADLE_VERSION} ${GRADLE_HOME}

FROM azul/zulu-openjdk:${ZULU_VERSION}

ENV GRADLE_HOME=/opt/gradle
ENV PATH="${GRADLE_HOME}/bin:${PATH}"

COPY --from=build /opt/gradle /opt/gradle