ARG ZULU_VERSION=8u492-jdk
FROM azul/zulu-openjdk-alpine:${ZULU_VERSION}

ENV GRADLE_HOME=/opt/gradle

ARG GRADLE_VERSION=7.6.6

RUN wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip  \
    && unzip gradle-${GRADLE_VERSION}-bin.zip  \
    && rm -rf gradle-${GRADLE_VERSION}-bin.zip  \
    && mv "gradle-${GRADLE_VERSION}" "${GRADLE_HOME}/"  \
    && ln -s "${GRADLE_HOME}/bin/gradle" /usr/bin/gradle
