FROM oraclelinux:8-slim
LABEL maintainer="jackkke hangao1204@hotmail.com"

WORKDIR /workspace

COPY docker-entrypoint.sh /usr/local/bin/

RUN microdnf -y update  \
    && microdnf -y install gcc glibc-devel zlib-devel wget gzip  \
    && chmod +x /usr/local/bin/docker-entrypoint.sh  \
    && wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz  \
    && wget https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-aarch64_bin.tar.gz  \
    && tar -zxf apache-maven-3.9.9-bin.tar.gz  \
    && tar -zxf graalvm-jdk-21_linux-aarch64_bin.tar.gz  \
    && mv graalvm-jdk-21.0.4+8.1 /etc/alternatives/graalvm-jdk-21.0.4+8.1  \
    && mv apache-maven-3.9.9 /etc/alternatives/apache-maven-3.9.9  \
    && rm -rf apache-maven-3.9.9-bin.tar.gz  \
    && rm -rf graalvm-jdk-21_linux-aarch64_bin.tar.gz  \
    && microdnf clean all

    ENV JAR_NAME=test

    VOLUME ["/workspace","/root/.m2/settings.xml"]
    
    ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]