FROM oraclelinux:7-slim
LABEL maintainer="jackkke hangao1204@hotmail.com"

WORKDIR /workspace

COPY docker-entrypoint.sh /usr/local/bin/

RUN yum -y update  \
    && yum -y install oracle-graalvm-ce-release-el7  \
    && yum -y install gcc glibc-devel zlib-devel wget gzip graalvm-community-21-jdk  \
    && chmod +x /usr/local/bin/docker-entrypoint.sh  \
    && wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz  \
    && tar -zxf apache-maven-3.9.9-bin.tar.gz -C /etc/alternatives  \
    && rm -f apache-maven-3.9.9-bin.tar.gz  \
    && yum clean all

ENV MAVEN_HOME=/etc/alternatives/apache-maven-3.9.9
ENV PATH=$MAVEN_HOME/bin:$PATH
ENV JAR_NAME=test

VOLUME ["/workspace","/root/.m2/settings.xml"]

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]