ARG ORACLELINUX_VERSION=8
FROM oraclelinux:${ORACLELINUX_VERSION}-slim
LABEL maintainer="jackkke hangao1204@hotmail.com"
ARG ORACLELINUX_VERSION=8

WORKDIR /workspace

COPY docker-entrypoint.sh /usr/local/bin/

RUN microdnf update -y  \
    && echo "" >> /etc/yum.repos.d/oracle-linux-ol${ORACLELINUX_VERSION}.repo  \
    && echo "[ol${ORACLELINUX_VERSION}_graalvm_community]" >> /etc/yum.repos.d/oracle-linux-ol${ORACLELINUX_VERSION}.repo  \
    && echo "name=Oracle GraalVM Community for Oracle Linux \$releasever (\$basearch)" >> /etc/yum.repos.d/oracle-linux-ol${ORACLELINUX_VERSION}.repo  \
    && echo "baseurl=https://yum\$ociregion.\$ocidomain/repo/OracleLinux/OL${ORACLELINUX_VERSION}/graalvm/community/\$basearch/" >> /etc/yum.repos.d/oracle-linux-ol${ORACLELINUX_VERSION}.repo  \
    && echo "gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle" >> /etc/yum.repos.d/oracle-linux-ol${ORACLELINUX_VERSION}.repo  \
    && echo "gpgcheck=1" >> /etc/yum.repos.d/oracle-linux-ol${ORACLELINUX_VERSION}.repo  \
    && echo "enabled=1" >> /etc/yum.repos.d/oracle-linux-ol${ORACLELINUX_VERSION}.repo  \
    && microdnf -y install gcc glibc-devel zlib-devel wget gzip graalvm-community-21-jdk  \
    && chmod +x /usr/local/bin/docker-entrypoint.sh  \
    && wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz  \
    && tar -zxf apache-maven-3.9.9-bin.tar.gz -C /etc/alternatives  \
    && rm -f apache-maven-3.9.9-bin.tar.gz  \
    && microdnf clean all

ENV MAVEN_HOME=/etc/alternatives/apache-maven-3.9.9
ENV PATH=$MAVEN_HOME/bin:$PATH
ENV JAR_NAME=test

VOLUME ["/workspace","/root/.m2/settings.xml"]

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]