ARG GRAALVM_VERSION=21.0.2
ARG ORACLELINUX_VERSION=9
FROM jackkke/graalvm:${GRAALVM_VERSION}-ol${ORACLELINUX_VERSION}
LABEL maintainer="jackkke hangao1204@hotmail.com"

RUN curl -o apache-maven-3.9.9-bin.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz  \
    && tar -zxf apache-maven-3.9.9-bin.tar.gz -C /etc/alternatives  \
    && ln -s /etc/alternatives/apache-maven-3.9.9/bin/mvn /bin/mvn  \
    && rm -f apache-maven-3.9.9-bin.tar.gz