ARG GRAALVM_VERSION=21.0.2
ARG ORACLELINUX_VERSION=9
FROM jackkke/graalvm-maven:${GRAALVM_VERSION}-ol${ORACLELINUX_VERSION}
LABEL maintainer="jackkke hangao1204@hotmail.com"

WORKDIR /workspace

COPY docker-entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENV JAR_NAME=test

VOLUME ["/workspace","/root/.m2"]

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]