name: Publish Chat2DB Image To Github

on:
  workflow_dispatch:
    inputs:
      chat2db_version:
        description: '输入 Chat2DB 版本号'
        required: true
        default: '3.4.1'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: chat2db
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:chat2db"
          push: true
          build-args: |
            VERSION=${{ github.event.inputs.chat2db_version }}
          tags: jackkke/pangu-mariadb:${{ github.event.inputs.chat2db_version }}-alpine,jackkke/chat2db
          file: Dockerfile