name: Publish GraalVM Image To Github

on:
  workflow_dispatch:
    inputs:
      jdk_version:
        description: '输入 JDK 版本号'
        required: true
        default: '21.0.2'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        oracle_linux_version: [ 7, 8, 9 ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build GraalVM Image Oracle Linux ${{ matrix.oracle_linux_version }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: "{{defaultContext}}:graalvm"
          build-args: |
            ORACLELINUX_VERSION=${{ matrix.oracle_linux_version }}
            GRAALVM_VERSION=${{ github.event.inputs.jdk_version }}
          tags: jackkke/graalvm:${{ github.event.inputs.jdk_version }}-ol${{ matrix.oracle_linux_version }},jackkke/graalvm:21-ol${{ matrix.oracle_linux_version }}
          file: Dockerfile
          push: true
      - name: Build GraalVM Maven Image Oracle Linux ${{ matrix.oracle_linux_version }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:graalvm"
          build-args: |
            ORACLELINUX_VERSION=${{ matrix.oracle_linux_version }}
            GRAALVM_VERSION=${{ github.event.inputs.jdk_version }}
          tags: jackkke/graalvm:${{ github.event.inputs.jdk_version }}-ol${{ matrix.oracle_linux_version }}-maven,jackkke/graalvm:21-ol${{ matrix.oracle_linux_version }}-maven,jackkke/graalvm-maven:${{ github.event.inputs.jdk_version }}-ol${{ matrix.oracle_linux_version }},jackkke/graalvm-maven:21-ol${{ matrix.oracle_linux_version }}
          file: Dockerfile-maven
          push: true
      - name: Build GraalVM Maven Build Image Oracle Linux ${{ matrix.oracle_linux_version }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:graalvm"
          build-args: |
            ORACLELINUX_VERSION=${{ matrix.oracle_linux_version }}
            GRAALVM_VERSION=${{ github.event.inputs.jdk_version }}
          tags: jackkke/graalvm:${{ github.event.inputs.jdk_version }}-ol${{ matrix.oracle_linux_version }}-build,jackkke/graalvm:21-ol${{ matrix.oracle_linux_version }}-build,jackkke/graalvm-maven:${{ github.event.inputs.jdk_version }}-ol${{ matrix.oracle_linux_version }}-build,jackkke/graalvm-maven:21-ol${{ matrix.oracle_linux_version }}-build
          file: Dockerfile-maven-build
          push: true