name: Publish Iandsec Base Image To Github

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "RockyLinux"
            tag: "9.5.20241127"
            file: "Dockerfile"
          - name: "RockyLinux minimal"
            tag: "9.5.20241127-minimal"
            file: "Dockerfile-minimal"
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: iandsec
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:iandsec-rockylinux"
          push: true
          tags: jackkke/iandsec-base:${{ matrix.tag }}
          file: ${{ matrix.file }}